"""voice_channels

Revision ID: 395795ef2728
Revises: e8b5bf0cd1f4
Create Date: 2026-03-25 08:41:08.435429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '395795ef2728'
down_revision: Union[str, Sequence[str], None] = 'e8b5bf0cd1f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_channels',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('server_id', sa.BigInteger(), nullable=False),
    sa.Column('kdr_role_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_channels_kdr_role_id'), 'voice_channels', ['kdr_role_id'], unique=False)
    op.create_index(op.f('ix_voice_channels_server_id'), 'voice_channels', ['server_id'], unique=False)
    op.add_column('kd_roles', sa.Column('channel_name', sa.String(), nullable=True))
    op.add_column('server_settings', sa.Column('category_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server_settings', 'category_id')
    op.drop_column('kd_roles', 'channel_name')
    op.drop_index(op.f('ix_voice_channels_server_id'), table_name='voice_channels')
    op.drop_index(op.f('ix_voice_channels_kdr_role_id'), table_name='voice_channels')
    op.drop_table('voice_channels')
    # ### end Alembic commands ###
