"""add settings table

Revision ID: b8035ea3f1d4
Revises: 3c93bb5d292f
Create Date: 2026-03-13 08:38:09.061353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8035ea3f1d4'
down_revision: Union[str, Sequence[str], None] = '3c93bb5d292f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_settings',
    sa.Column('server_id', sa.BigInteger(), nullable=False),
    sa.Column('log_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('server_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('server_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('server_settings')
    # ### end Alembic commands ###
