"""add modes

Revision ID: e8b5bf0cd1f4
Revises: b8035ea3f1d4
Create Date: 2026-03-14 09:13:29.867865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8b5bf0cd1f4'
down_revision: Union[str, Sequence[str], None] = 'b8035ea3f1d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server_settings', sa.Column('mode', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server_settings', 'mode')
    # ### end Alembic commands ###
